export const API_LOGIN_REQUEST = 'API_LOGIN_REQUEST';
export const API_LOGIN_SUCCESS = 'API_LOGIN_SUCCESS';
export const API_LOGIN_FAILURE = 'API_LOGIN_FAILURE';
export const API_REGISTER_REQUEST = 'API_REGISTER_REQUEST';
export const API_REGISTER_SUCCESS = 'API_REGISTER_SUCCESS';
export const API_REGISTER_FAILURE = 'API_REGISTER_FAILURE';

export const SET_LANGUAGE = 'SET_LANGUAGE';
export const LOGOUT = 'LOGOUT';
