export const API_LOGIN_REQUEST = 'API_LOGIN_REQUEST';
export const API_LOGIN_SUCCESS = 'API_LOGIN_SUCCESS';
export const API_LOGIN_FAILURE = 'API_LOGIN_FAILURE';
export const API_REGISTER_REQUEST = 'API_REGISTER_REQUEST';
export const API_REGISTER_SUCCESS = 'API_REGISTER_SUCCESS';
export const API_REGISTER_FAILURE = 'API_REGISTER_FAILURE';
export const API_EDIT_USER_REQUEST = 'API_EDIT_USER_REQUEST';
export const API_EDIT_USER_SUCCESS = 'API_EDIT_USER_SUCCESS';
export const API_EDIT_USER_FAILURE = 'API_EDIT_USER_FAILURE';

export const API_PATIENT_INFO_REQUEST = 'API_PATIENT_INFO_REQUEST';
export const API_PATIENT_INFO_SUCCESS = 'API_PATIENT_INFO_SUCCESS';
export const API_PATIENT_INFO_FAILURE = 'API_PATIENT_INFO_FAILURE';

export const API_MEDICAL_INFO_REQUEST = 'API_MEDICAL_INFO_REQUEST';
export const API_MEDICAL_INFO_SUCCESS = 'API_MEDICAL_INFO_SUCCESS';
export const API_MEDICAL_INFO_FAILURE = 'API_MEDICAL_INFO_FAILURE';

export const API_CLINICS_SEARCH_REQUEST = 'API_CLINICS_SEARCH_REQUEST';
export const API_CLINICS_SEARCH_SUCCESS = 'API_CLINICS_SEARCH_SUCCESS';
export const API_CLINICS_SEARCH_FAILURE = 'API_CLINICS_SEARCH_FAILURE';

export const API_PENDING_USERS_REQUEST = 'API_PENDING_USERS_REQUEST';
export const API_PENDING_USERS_SUCCESS = 'API_PENDING_USERS_SUCCESS';
export const API_PENDING_USERS_FAILURE = 'API_PENDING_USERS_FAILURE';

export const API_HANDLE_USER_REGISTRATION_REQUEST = 'API_HANDLE_USER_REGISTRATION_REQUEST';
export const API_HANDLE_USER_REGISTRATION_SUCCESS = 'API_HANDLE_USER_REGISTRATION_SUCCESS';
export const API_HANDLE_USER_REGISTRATION_FAILURE = 'API_HANDLE_USER_REGISTRATION_FAILURE';

export const SET_LANGUAGE = 'SET_LANGUAGE';
export const LOGOUT = 'LOGOUT';
export const SET_AUTH_NAV_BAR = 'SET_AUTH_NAV_BAR';
